### ISSUE TITLE
unkown emoji

### ISSUE THREAD

**Issue by dgradecak** [DenisIndenbom/DiscordAuth#9]
hi,

I am trying to setup this auth plugin for my son's server but there is an "unknown emjoi" exception

https://github.com/DenisIndenbom/DiscordAuth/blob/430b8c99a07b60ebec1eff5d14ef5889538c3210/src/main/java/com/denisindenbom/discordauth/discord/Bot.java#L52

I am running bukkit mc in docker (linux), by any chance do you know how to fix this? whitelist is disabled

this is the stack trace:

```
mc_1  | [08:32:16] [Server thread/INFO]: dgradecak (/188.252.168.127:54438) lost connection: You are not white-listed on this server!
mc_1  | [08:32:17] [ForkJoinPool.commonPool-worker-2/ERROR]: RestAction queue returned failure: [ErrorResponseException] 10014: Unknown Emoji
mc_1  | net.dv8tion.jda.api.exceptions.ContextException: null
mc_1  |         at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[?:?]
mc_1  |         at net.dv8tion.jda.api.requests.Request.<init>(Request.java:72) ~[?:?]
mc_1  |         at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197) ~[?:?]
mc_1  |         at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572) ~[?:?]
mc_1  |         at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538) ~[?:?]
mc_1  |         at com.denisindenbom.discordauth.discord.Bot.sendLoginConfirmRequest(Bot.java:52) ~[?:?]
mc_1  |         at com.denisindenbom.discordauth.DiscordAuth.registerLoginConfirmationRequest(DiscordAuth.java:146) ~[?:?]
mc_1  |         at com.denisindenbom.discordauth.listeners.PlayerListener.onPlayerLogin(PlayerListener.java:70) ~[?:?]
```

**Comment by DenisIndenbom** [comment]
Hi, 

U can try this `message.addReaction("U+2705").queue();`

I have an idea that Linux cannot support emoji in code.

**Comment by dgradecak** [comment]
yes, I was already compling with that unicode and it is working.
Thank you for this work, quite useful for the kids because they got their server "hacked" !
